server:
  servlet:
    context-path: /assistant #根路径

spring:  datasource: #数据库基本配置    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.izumieita.cn:3306/assistant?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: IZUMIeita@mysql24
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jpa:    show-sql: true #启用SQL语句的日志记录    
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #设置方言
    database-platform: com.mupei.assistant.config.MySQLConfig #设置方言
    hibernate:      ddl-auto: update #自动生成数据表的方式    properties:      hibernate:
        format_sql: true #格式化SQL语句   
#        dialect:
#          storage_engine: innodb
  mvc:    date-format: yyyy-MM-dd HH:mm:ss #mvc接收参数时对日期进行格式化 
  jackson:    date-format: yyyy-MM-dd HH:mm:ss #jackson对响应回去的日期参数进行格式化
    time-zone: GMT+8
  thymeleaf:    cache: true
  devtools:    restart:      enabled: true #热部署devtools开启
      exclude: src/main/resources #排除监听该目录
      additional-paths:      - src/main/java #监听目录
  resources: #资源文件访问路径    static-locations:    - /META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - classpath:/templates/  profiles:    active:    - dev #激活开发环境  mail:    default-encoding: utf-8
    host: smtp.qq.com
    username: 2980085672@qq.com
    password: eglotpcuzsxbddig
    properties:
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  redis:   
    database: 0 # Redis数据库索引（默认为0)
    host: 127.0.0.1 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    password: #Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 200 #连接池最大连接数 
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）  
        max-idle: 10 #连接池中的最大空闲连接  
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 30000 #连接超时时间（毫秒）

logging: #日志输出
  level:    com.mupei.assistant: trace #输出日志最低级别#  path: /spring-assistant/log #指定目录，日志名默认spring.log；在当前磁盘的根目录下开始创建
  file: F:/assistant-log/assistant.log #不指定路径-当前项目下生成日志；指定完整路径-按路径生成日志
#  pattern:#    console: #设置控制台的日志输出格式
#    file: #设置文件中的日志输出格式
